spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lp1p2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
#  main:
#    web-application-type: none
  application:
    ui:
      title: lp1p2